# Site Configuration
title: Touhid Shaikh's Portfolio
email: touhidshaikh22@gmail.com
description: A cybersecurity professional with 6+ years of experience. Expert in identifying critical vulnerabilities (RCE, Auth Bypass) in hardware and enterprise software. Active contributor to <span class="highlight">Metasploit</span> and <span class="highlight">Exploit-DB</span>, with 10+ published exploits. Primary author of the official CIS pfSense Benchmark. Creator of <span class="highlight">403Override-NG</span>.
url: "https://touhidshaikh.com"
baseurl: ""
rss2json_api_key: "1whfh8wh55x5cennpqvqbxyxraacat1ifc0bzonq"
drive_link_resume: "https://drive.google.com/file/d/1rHgy67Tbss9N21ltn_MpoPOwmxMb1UyC/view?usp=sharing"

# Personal Details
author:
  name: Touhid M Shaikh
  role: Security_Researcher // Exploit_Developer // Open_Source_Contributor
  location: Mumbai, IN
  ip_address: "127.0.0.1"
  pgp_public_key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Comment: User ID:	Touhid Shaikh <touhidshaikh22@gmail.com>
    Comment: Valid from:	17-04-2026 05:21
    Comment: Valid until:	17-04-2029 12:00
    Comment: Type:	255-bit EdDSA (secret key available)
    Comment: Usage:	Signing, Encryption, Certifying User IDs
    Comment: Fingerprint:	7DC4 4A70 1D41 FC60 484B  5B8D F28D 01E0 2476 8F34
    
    
    mDMEaeF2HBYJKwYBBAHaRw8BAQdAy8wXqO4g06ve+gGa4McUyYKZom8249/gHTm2
    aS0SCi60KFRvdWhpZCBTaGFpa2ggPHRvdWhpZHNoYWlraDIyQGdtYWlsLmNvbT6I
    tQQTFgoAXRYhBH3ESnAdQfxgSEtbjfKNAeAkdo80BQJp4XYcGxSAAAAAAAQADm1h
    bnUyLDIuNSsxLjEyLDIsMQIbAwUJBaVJTAULCQgHAgIiAgYVCgkICwIEFgIDAQIe
    BwIXgAAKCRDyjQHgJHaPNL4RAP9xLGYq024XApNFAVvblLEZOVtZjRdy16Cnnw+a
    x0cHIgEAyyPlun2Xr4AXXbjQy2o5e4OOxyyCTno428Gs+uBCkwW4OARp4XYcEgor
    BgEEAZdVAQUBAQdAbZCiv6/RQ8kiP2YVHlj9Y17bhoN24wN43q63aJiIZB8DAQgH
    iJoEGBYKAEIWIQR9xEpwHUH8YEhLW43yjQHgJHaPNAUCaeF2HBsUgAAAAAAEAA5t
    YW51MiwyLjUrMS4xMiwyLDECGwwFCQWlSUwACgkQ8o0B4CR2jzSmdAEA8uTE2cNC
    xh1xyLhSFGz85yx5fkdT9e7cRf2ouGJgRKQA/jP5M+XfBDc7hAApg4jv08gSCbot
    oCizJo116+cA8JMG
    =wFd6
    -----END PGP PUBLIC KEY BLOCK-----

# Specializations skills
skills: ["VAPT", "Network_Security", "WEB_EXPLOIT", "PYTHON_AUTOMATION"]

# Social Links
social:
  github: "touhidshaikh"
  linkedin: "touhidshaikh22"
  twitter: "touhidshaikh22"
  hackthebox: "10931"
  bugcrowd_url: "https://bugcrowd.com/h/touhidshaikh"

# Certifications
certifications: 
  - name: "OSCP"
    url: "https://www.credential.net/ccb32fa5-8b6b-4ca9-8721-e33cca843472#acc.xTLpGCw7"

  - name: "OSCE"
    url: "https://www.credential.net/f796318c-32c6-464b-abeb-e37540ca9ccb"

  - name: "CREST CRT"
    url: "#"

  - name: "CPSA"
    url: "#"

# Hall of Fame
hall_of_fame: 
  - name: "APPLE"
    url: "https://support.apple.com/en-us/HT201536"
  - name: "NETGEAR"
    url: "https://bugcrowd.com/netgear/hall-of-fame"
  - name: "SYNOLOGY"
    url: "https://www.synology.com/en-global/security/hall_of_fame"
  - name: "ONEPLUS"
    url: "https://security.oneplus.com/hall-of-fame.html"
