# Site Configuration
title: TOUHID SHAIKH | SECURITY RESEARCHER
email: touhidshaikh22@gmail.com
description: A cybersecurity professional with 6+ years of experience. Expert in identifying critical vulnerabilities (RCE, Auth Bypass) in hardware and enterprise software. Active contributor to <span class="highlight">Metasploit</span> and <span class="highlight">Exploit-DB</span>, with 10+ published exploits. Primary author of the official CIS pfSense Benchmark. Creator of <span class="highlight">403Override-NG</span>.
url: "https://touhidshaikh.com"
baseurl: ""
rss2json_api_key: "1whfh8wh55x5cennpqvqbxyxraacat1ifc0bzonq"

# Personal Details
author:
  name: Touhid M Shaikh
  role: Security_Researcher // Exploit_Developer // Open_Source_Contributor
  location: Mumbai, IN
  ip_address: "127.0.0.1"
  pgp_public_key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    [INSERT_YOUR_PGP_KEY_HERE]
    -----END PGP PUBLIC KEY BLOCK-----

# Specializations skills
skills: ["VAPT", "Network_Security", "WEB_EXPLOIT", "PYTHON_AUTOMATION"]

# Social Links
social:
  github: "touhidshaikh"
  linkedin: "touhidshaikh22"
  twitter: "touhidshaikh22"
  hackthebox: "10931"
  bugcrowd: "https://bugcrowd.com/h/touhidshaikh"

# Certifications
certifications: 
  - name: "OSCP"
    url: "https://www.credential.net/ccb32fa5-8b6b-4ca9-8721-e33cca843472#acc.xTLpGCw7"

  - name: "OSCE"
    url: "https://www.credential.net/f796318c-32c6-464b-abeb-e37540ca9ccb"

  - name: "CREST CRT"
    url: "#"

  - name: "CPSA"
    url: "#"

# Hall of Fame
hall_of_fame: 
  - name: "APPLE"
    url: "https://support.apple.com/en-us/HT201536"
  - name: "NETGEAR"
    url: "https://bugcrowd.com/netgear/hall-of-fame"
  - name: "SYNOLOGY"
    url: "https://www.synology.com/en-global/security/hall_of_fame"
  - name: "ONEPLUS"
    url: "https://security.oneplus.com/hall-of-fame.html"